### ISSUE TITLE
Publish a nuget package with the fix for #99

### ISSUE THREAD

**Issue by Guymestef** [T4MVC/R4MVC#101]
Hello,

Can we publish a new alpha version?
Currently R4MVC cannot work with dotnet core sdk 1.2.300 and the fix #99 of @valeriob for the version 1.2.300-rc should fix this, no?

**Comment by artiomchi** [comment]
Oh shoot, of course! I thought I pushed the merge to the alpha branch, but I clearly forgot to do it.

Also, for some reason I keep not getting the GitHub notifications in my main mail account, so I just noticed this issue, sorry.

I just pushed the latest build to NuGet, so it should be available shortly
