### ISSUE TITLE
We've blown the storage on the MyGet feed

### ISSUE THREAD

**Issue by kevinkuszyk** [T4MVC/R4MVC#102]
Hey @artiomchi, I had an email the other day from MyGet saying that we've burnt through the 500MB of storage we have there (we're now at 650MB).

Any objections if I cull some of the older packages, and add a package retention policy?  I was thinking keep the last 20 versions, but don't delete if someone has downloaded it?

**Comment by kevinkuszyk** [comment]
http://docs.myget.org/docs/reference/package-retention

**Comment by kevinkuszyk** [comment]
I've also applied for an OSS subscription which will give us 1GB storage.

**Comment by artiomchi** [comment]
Oh wow, I didn't even think that there would be a limit, but it does make sense!

Sure, that policy makes sense. It'll be a good start at least, and we'll see how soon we fill up the space again after that :)

**Comment by kevinkuszyk** [comment]
We're now back on the OSS subscription, so we have 1GB of storage.

The retention policy is working too, so we down to 317MB of storage used.
