### ISSUE TITLE
Compile Error when controller action is conditionally compiled for debug

### ISSUE THREAD

**Issue by jlddodger** [T4MVC/R4MVC#105]
If the project uses a conditional compilation symbol, it isn't clear how the R4MVC is aware of what symbols should be defined.  In my case it appears that DEBUG is defined for list controllers/actions, so when I build release I get errors failing to override the excluded actions.

```
public partial class MyController
{
#if DEBUG
   public virtual IActionResult Index()
   {
      return View();
   }
#endif
}
```
```
1>R4Mvc.generated.cs(2332,64,2332,69): error CS0115: 'R4MVC_MyController.Index()': no suitable method found to override
```

**Comment by artiomchi** [comment]
That's.... an interesting one

The way R4Mvc is checking what's in code is by analysing the code presented by the code analysers. I'll have to look and see if it's possible to identify preprocessor directives, but even if it is - I'm not sure what would be the correct course of action here.

Thinking what you're trying to achieve here - you don't want the Index action to be present in the release builds. So am I correct to assume that it's used for test pages during development, and you don't really have any links to said pages?

If that's the case, wouldn't it be best to mark these actions with the `[R4MvcExclude]` attribute? This seems to me like it would be the best course of action

**Comment by jlddodger** [comment]
Yeah.  That would work.  I missed that attribute.  Currently the attribute only functions on controller classes.  Would it be possible to have the attribute for individual actions?

**Comment by artiomchi** [comment]
Oh.. DAMN, you're right?

/facepalm

Sorry, of course. I'll patch that as soon as I can, sorry for that

**Comment by jlddodger** [comment]
Cool.  Thanks for the response.  I can get by for now by excluding whole controllers or moving individual actions, but it'll be easier with an action attribute.

Thanks!
