### ISSUE TITLE
Add supports ActionResult<T> as action result type

### ISSUE THREAD

**Issue by jack128** [T4MVC/R4MVC#107]
Hi.

I thinks it's easy to add this feature, just add this line

```csharp
else if (methodReturnType.InheritsFrom<RedirectToRouteResult>())
   callInfoType = Constants.RedirectToRouteResultClass;
else if (methodReturnType.ToString().StartsWith("Microsoft.AspNetCore.Mvc.ActionResult<")) { } // !!!! added by me
```
in AddMethodOverrides method

**Comment by artiomchi** [comment]
Hey, that's a great point. I was going to make a release pretty soon with some other changes, I'll try to squeeze that in!

**Comment by jack128** [comment]
Actually also need to add overload
protected RedirectToRouteResult RedirectToAction(IConvertToActionResult result)

**Comment by artiomchi** [comment]
Pretty much on point :)

I just had to add a whole bunch of extension methods to the `R4Mvc` project, and make it only available on newer frameworks
