### ISSUE TITLE
Expired NuGet API keys

### ISSUE THREAD

**Issue by artiomchi** [T4MVC/R4MVC#109]
Hey @kevinkuszyk,

Since I don't have any other way to contact you, I'll open an issue :)

Seems like the API keys you issued for NuGet have expired. Could you double check that, and generate new keys, encrypt them in the AppVeyor account, and update the appveyor.yml file with the new secured key?

Also, the latest cut is going to add another package that we'll be publishing to NuGet. Could you add me as a package owner there? Better yet, seems like NuGet now has the concept of [Organisations](https://docs.microsoft.com/en-us/nuget/reference/organizations-on-nuget-org), so that might be worth looking into as well?

**Comment by kevinkuszyk** [comment]
Hello there!

Apologies for the expired API key.  I've just pasted a new one into the `appveyor.yml` in the `develop` branch.

I've also created a R4MVC org on nuget and added you as an admin.  Fyi - you were already listed as a package owner in nuget.

Feel free to ping me when the new package is published, and I'll add it to the org if it doesn't go in automatically.

**Comment by kevinkuszyk** [comment]
And an update - I just spotted how to create a nuget api key for an org account - so I've switch the `appveyor.yml` over to use an api key owned by the R4MVC nuget org. 

As you're an admin of the org, you should be able to manage it, and the new package will be owned by it, so it should all "just work".

**Comment by artiomchi** [comment]
As far as I remember, NuGet doesn't let us create non expiring keys, so when the current one expires, I might ask you to secure it in the AppVeyor account again :)

Great news otherwise, thanks for setting it up!

I just merged dev to the prerelease branch, and the deployment went ahead and published the new versions on NuGet!

**Comment by kevinkuszyk** [comment]
No probs.  As always, ping me if you need a hand with it next time.
