### ISSUE TITLE
virtual keyword added to override method

### ISSUE THREAD

**Issue by gmoneh** [T4MVC/R4MVC#110]
Suppose you have controller DerivedController which derives from BaseController. BaseController declares a virtual action method public virtual ActionResult VirtualAction(), which DerivedController proceeds to override via public override ActionResult VirtualAction().
After generating R4MVC, the method in DerivedController is changed to public override virtual VirtualAction(), which is obviously incorrect syntactically.
R4MVC should not add the virtual keyword if a method is already an override.

**Comment by artiomchi** [comment]
Sorry that I didn't have time to check in and take a look at the issue myself. And thanks for submitting a PR to fix it!

I'm close to finishing support for Razor Pages, and I'll make a new release soon after that, which will include this patch!

**Comment by gmoneh** [comment]
That's alright, glad to contribute. That's what open source software is for, right?
