### ISSUE TITLE
Does not seem to work with vs 2019 RC2

### ISSUE THREAD

**Issue by valeriob** [T4MVC/R4MVC#116]
I have installed both vs2017 and vs2019, 

![image](https://user-images.githubusercontent.com/1522516/54594941-f70a2180-4a31-11e9-86fd-f5beef864c70.png)

**Comment by valeriob** [comment]
Hi,
can you generate a build for #117 pls ?

**Comment by artiomchi** [comment]
Absolutely.

I didn't merge it because I thought you said the patch didn't work?

**Comment by artiomchi** [comment]
I can see that you've been using .NET Core 3.0 preview in your build, so I updated the rest of the packages in the Tools project, and am pushing that to NuGet.

Let me know if that gets your build to work again

**Comment by valeriob** [comment]
Sorry if i made some confusion, the patch works 😄

**Comment by artiomchi** [comment]
Oh right, cool! Thanks for letting me know :)
