### ISSUE TITLE
MyGet Renewal

### ISSUE THREAD

**Issue by kevinkuszyk** [T4MVC/R4MVC#126]
@artiomchi it's that time of year again.  

Apologies - I missed their first email and our feed is now readonly.  I've sent the request in for a  renewal.  I'll update this issue when I hear back.

**Comment by artiomchi** [comment]
Hi @kevinkuszyk 

Thanks for taking care of this!

**Comment by artiomchi** [comment]
Hi @kevinkuszyk 

Could you sort out the NuGet publish keys when you get a moment, please? :)

**Comment by kevinkuszyk** [comment]
@artiomchi 09ed8f0 has the new nuget.org api keys.  If you rebase on that you should be able to push again.

Regarding myget - something has gone amiss with our open source licence.  I talking them to get it fixed.  In the meantime they are suggesting we delete some packages over there to bring us down under the 100MB storage limit.  If it's not blocking you at the moment, I think we should push back until they have the licence properly applied.  Thoughts?

**Comment by artiomchi** [comment]
@kevinkuszyk  thanks for sorting this out :)

Umm, I pushed some commits yesterday and they failed to push the CI builds because of space issue on MyGet. It's not critical, I guess, just means we wouldn't get any new CI builds on MyGet. With each build taking 10MB at the moment, even if you deleted all the packages, it would still take < 10 builds to take up all the space, so I don't think it would make sense to spend the time to clean it manually.

**Comment by valeriob** [comment]
We can just push it to nuget :D

**Comment by valeriob** [comment]
Hi, is it possible to upload the package to nuget ?

**Comment by kevinkuszyk** [comment]
@valeriob apologies, I'm a but out of the loop with what's happening over here.  Is the lack of myget blocking getting packages out to nuget? (I don't think we should publish ci builds there).

@artiomchi should we consider switching off myget until they have our licence sorted?  If yes, are you ok to make that change to the `appveyor.yml`?

**Comment by valeriob** [comment]
Hi @kevinkuszyk thanks for helping, this package is blocking everyone using r4mvc to start testing netcore 3.0, i think we can push it to nuget since the change is very small, and allow ppl to start testing the framework.

**Comment by kevinkuszyk** [comment]
@valeriob is there a build / commit / PR with this change in?

**Comment by valeriob** [comment]
yes, see commit https://github.com/T4MVC/R4MVC/commit/70e72f08f1ef3edf490cf3964145cd268e72c174

**Comment by artiomchi** [comment]
Hi,

I'm going to do a bit of cleaning of the code today, making sure it's
working well with .net core 3, merge the new PR, and will push to NuGet
within the next 12 hours

Sorry I didn't get a chance to do it earlier

**Comment by artiomchi** [comment]
I've just pushed the new build to NuGet. The PR is a bit more work, so I thought I'd better push a working build and deal with the PR a bit later.

Regarding MyGet - @kevinkuszyk GitHub added a new feature - a built-in [package registry](https://github.com/features/package-registry). It's currently in early preview, but do you think you could request access to it for R4Mvc? I've just tested it on one of my project, and it might just be a nice replacement to MyGet, keeping both the code and packages in one place.

**Comment by kevinkuszyk** [comment]
@valeriob with that new version @artiomchi pushed, I guess that's you sorted now?

@artiomchi re. myget - they've asked me to apply for the open source licence again, which I've done this morning.

And re. the GitHub package registry.  I've signed us up for the beta, and we're on the waiting list.

**Comment by valeriob** [comment]
Thanks ! should be fine !

**Comment by kevinkuszyk** [comment]
@artiomchi we're back on the open source subscription over a myget now, so the CI packages should be getting published again.

We've also been approved for the GitHub package registry if you want to have a poke around with that.

I'm going to close this issue now, as the myget is sorted.  If you need a hand / want to discuss the GitHub package registry, let's do that on a new ticket.
