### ISSUE TITLE
Reference to type 'RouteValueDictionary' claims it is defined in 'Microsoft.AspNetCore.Routing.Abstractions', but it could not be found

### ISSUE THREAD

**Issue by valeriob** [T4MVC/R4MVC#130]
Hi,
i'm testing netcore3.0 preview 9, and i think there is something to be done to make r4mvc compatible.

![image](https://user-images.githubusercontent.com/1522516/64770233-113e3b80-d54d-11e9-9694-423b2092fe7d.png)

**Comment by valeriob** [comment]
Did you have time to test dotnet core 3.0 ? 😄

**Comment by artiomchi** [comment]
Hey @valeriob 

Yup, I just set up the beta version on my PC and am looking into this 😄

**Comment by valeriob** [comment]
ah good, i found 15' to check it and i was about to push a pull request, i think we can drop the support for aspnetcore 1.0 to be honest, and push the framework version up to 4.7.2 that properly support netstandard2.0, everything before that is a mess :D

**Comment by artiomchi** [comment]
The problem in this case is that they moved `RouteValueDictionary` from `Microsoft.AspNetCore.Routing.Abstractions` to `Microsoft.AspNetCore.Http.Abstractions` in the v3 assemblies.

I'm just checking if I can solve this with multitargetting, or a major version release with different references would be required :)
The annoying thing is that the new version isn't even on NuGet - it's only currently published to MyGet :D

**Comment by valeriob** [comment]
aspnet core 3.0 will not run on other framework than dotnet core 3.0, so i would go with this route, no need for nuget packages.
`  <ItemGroup Condition="'$(TargetFramework)'=='netcoreapp3.0'">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>`

**Comment by artiomchi** [comment]
Yup, I just realised that as well.. The reference libraries aren't even on their MyGet servers, but referencing the framework reference works well.

**Comment by artiomchi** [comment]
The build server was failing to build this, even with the preview 2019 images :D

I made the build script install the latest .net core sdk before the build, which seems to have worked, but I can't upload the images to neither MyGet (the nupkg file is too big) or NuGet (the key is expired).

I'll ping Kevin to have the key sorted out :)

**Comment by valeriob** [comment]
awesome !

**Comment by rbsdotnet** [comment]
Hi,

What is the solution to this problem?

**Comment by rbsdotnet** [comment]
Hi,

I received your project and made the following changes to the project
And it runs on .net core 3 without any problems

** These changes are for .net core 3 only **

1: R4Mvc
[R4Mvc.txt](https://github.com/T4MVC/R4MVC/files/3660435/R4Mvc.txt)
................................................................................................
2.R4Mvc.Tools
[R4Mvc.Tools.txt](https://github.com/T4MVC/R4MVC/files/3660438/R4Mvc.Tools.txt)
................................................................................................
3.R4Mvc.Tools.Cli
[R4Mvc.Tools.Cli.txt](https://github.com/T4MVC/R4MVC/files/3660439/R4Mvc.Tools.Cli.txt)

-----------------------------------------------------------------------------------------
But when we get the project from nuget there is a problem with not recognizing Microsoft.AspNetCore.Mvc in your project
Which I think you need to change its namespace to not interfere with Microsoft.AspNetCore.Mvc 3.0

**Comment by mahdi-ataollahi** [comment]
URGENT HELP! Please fix it ASAP. I upgraded my project to .net core 3 and the only thing remained is R4MVC. Thanks!

Is there any temporarily solution?

**Comment by artiomchi** [comment]
@valeriob @mahdi-ataollahi Sorry for the delay - I've pushed a new build to NuGet that has support for ASP.Net core - let me know if it works well for you, or if you're having any issues

**Comment by rbsdotnet** [comment]
@artiomchi 
Thanks for the quick release of the new version
