### ISSUE TITLE
Ignor Controller Or Action

### ISSUE THREAD

**Issue by rbsdotnet** [T4MVC/R4MVC#131]
Hi,

How to Ignor Controller Or Action to Generate?

**Comment by artiomchi** [comment]
Hi @rbsdotnet 

You can use the `[R4MVCExclude]` attribute on actions or controllers to exclude them from R4Mvc generation.

You can see examples in the sample projects:
https://github.com/T4MVC/R4MVC/blob/develop/samples/AspNetSimple/Controllers/TestsController.cs
