### ISSUE TITLE
Code generation fails on ASP.NET Core 3.0

### ISSUE THREAD

**Issue by btihanyi** [T4MVC/R4MVC#132]
I've tested the new release with an ASP.NET Core 3.0 project, but R4MVC throws an error while generating the code. I've also tested with the AspNetSimple.NetCore3 project, but with the same result. Then I checked the source code and found out that the `ReferencedAssemblyNames` do not contain the Microsoft.AspNetCore.Mvc reference, nor any similar values. So this code
```
// Get MVC version
var mvcAssembly = compilation.ReferencedAssemblyNames
    .Where(a => a.Name == "Microsoft.AspNetCore.Mvc")
    .FirstOrDefault();
```
will always assign `mvcAssembly` a null value for 3.0 projects, then throw a `NullReferenceException`. I wonder if there is any other way to get the framework's version?

**Comment by artiomchi** [comment]
You must have a build error or something, because it detects the reference correctly on all my environments, as well as on the build server.

You can see the latest build log here: https://ci.appveyor.com/project/T4MVC/r4mvc

If you scroll down, you can find this extract:

```
C:\projects\r4mvc>.\src\R4Mvc.Tools\bin\Release\net472\R4Mvc.Tools.exe generate -p .\samples\AspNetSimple.NetCore3\AspNetSimple.NetCore3.csproj 
  R4Mvc Generator Tool v1.0.0

Using: Visual Studio Community 2019 - 16.3.29326.143
Project: C:\projects\r4mvc\samples\AspNetSimple.NetCore3\AspNetSimple.NetCore3.csproj

Creating Workspace ...
Loading project ...
Compiling project ...
Detected MVC version: 3.0.0.0

Processing controller AspNetSimple.NetCore3.Controllers.HomeController

Generating \Controllers\HomeController.generated.cs
Generating \R4Mvc.generated.cs

Operation completed in 00:00:09.4649861
```

Are you sure you have the 3.0 SDK installed, and not just the runtime on your machine?

**Comment by btihanyi** [comment]
I have installed the full 3.0 SDK with the Visual Studio 2019, however I also have the 2017 version installed on my machine. I've figured out that the R4Mvc tool was using the old Visual Studio instance, but I've managed to specify the proper version via the `-vsi` command line argument. Now it seems to be working properly.
