### ISSUE TITLE
Controllers are not processed properly on ASP.NET Core 3.0

### ISSUE THREAD

**Issue by btihanyi** [T4MVC/R4MVC#133]
It seems that in an ASP.NET 3.0 project, controllers (and pages) are not generated properly. The problem is that MVC types like `BaseController` or `PageModel` are not recognized with different framework versions. However, changing the R4Mvc.Tools' TargetFramework to `netcoreapp3.0` would solve this issue.

**Comment by artiomchi** [comment]
That's not the case in our build environments, as well as the build server. See my comment from #132, as I think it might be the same issue in both tickets that you opened - are you sure you have the SDK installed properly?

**Comment by btihanyi** [comment]
It is working now as I specified the VS 2019 instance for the CLI tool.
