### ISSUE TITLE
Allow adding to list of #pragma warnings to suppress

### ISSUE THREAD

**Issue by MABrunner** [T4MVC/R4MVC#134]
I like to use Microsoft.CodeAnalysis.FxCopAnalyzers to improve code quality.  I also like to set TreatWarningsAsErrors to true.  However, because of the code generated by R4MVC, I'm unable to do this.  Some of the namespaces imported into the generated code are unused, causing warnings, which become errors.

Of course it would be nice if we had the T4 template to customize like we did back in the day, but I know that's not supported.  In the absence of that, we could add an option to the settings file to allow additional warning codes to be added, similar to the way additional namespaces can be added.

I created a very simple commit for this that I can push if given permission.

Thanks!

**Comment by artiomchi** [comment]
I just started using the analyzers package in a couple of my own projects, so I can definitely understand your situation.

I'm going to add it to the R4Mvc package eventually, but in the meantime - making the generated code avoid any warnings would be great. And any help in the project is always greatly appreciated!

If you fork the project, and create a Pull Request, we can absolutely merge it to the project

**Comment by MABrunner** [comment]
Awesome thanks!  I'll do that Monday.
