### ISSUE TITLE
dotnet tool install -g r4mvc.tools.cli fails

### ISSUE THREAD

**Issue by clement911** [T4MVC/R4MVC#140]
>  dotnet tool install -g r4mvc.tools.cli
> error NU1103: Unable to find a stable package r4mvc.tools.cli with version
> error NU1103:   - Found 7 version(s) in nuget.org [ Nearest version: 1.0.0-alpha2-00369 ]
> error NU1103:   - Found 0 version(s) in Microsoft Visual Studio Offline Packages
> error NU1103:   - Found 0 version(s) in C:\Program Files\dotnet\sdk\NuGetFallbackFolder
> The tool package could not be restored.
> Tool 'r4mvc.tools.cli' failed to install. This failure may have been caused by:
> 
> * You are attempting to install a preview release and did not use the --version option to specify the version.
> * A package by this name was found, but it was not a .NET Core tool.
> * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
> * You mistyped the name of the tool.
> 
> For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

I was able to fix it by specifying a version:

`dotnet tool install -g --version 1.0.0-alpha2-00369 r4mvc.tools.cli`

Unless I missed something, this is not documented in the installation steps.

**Comment by artiomchi** [comment]
Hi @clement911

You're partially right - the [Installation](https://github.com/T4MVC/R4MVC/wiki/Installation) page on the wiki mentions the version parameter if you want to install a pre-release version. Unfortunately I haven't released a release one, and still marked them as pre-release, hence the error. I'm hoping to be able to do this soon. In the meantime, I'll update the documentation to be more specific about this.
