### ISSUE TITLE
Generate the URL for custom routing

### ISSUE THREAD

**Issue by ghost** [T4MVC/R4MVC#141]
How to generate the below URL Routing

                routes.MapRoute(
                   name: "defaultId",
                   template: "{controller=Home}/{id?}/{action=Index}");

**Comment by artiomchi** [comment]
Hi @VIJAYASHANKAR 

The URLs will be generated by MVC based on the routes you have created automatically.

With R4Mvc youb request a URL for a specific controller, action with a number of route parameters - the MVC framework will pick the **first** matching route from the list of routes you created, and will use it to generate a URL.

But that's all just how MVC works, R4Mvc doesn't do anything in regards to manipulating or picking routes
