### ISSUE TITLE
C#9 target-type new incompatibility

### ISSUE THREAD

**Issue by ceccacecca** [T4MVC/R4MVC#160]
Hi, I've just ran into an issue after using a new functionality specified by the new C#9 version.
The functionality is the **target-type new** expression, which allows you to initialize a variable in this way:
`ViewModel model = new();`

When using this notation, the whole area of the controller does not get generated and gives error.

Thanks.

**Comment by artiomchi** [comment]
I just released a new build yesterday that supports the latest version of Visual Studio, and it should now support this notation
