### ISSUE TITLE
Error in New Visual Studio Version

### ISSUE THREAD

**Issue by rbsdotnet** [T4MVC/R4MVC#161]
PM> Generate-R4MVC
  R4Mvc Generator Tool v1.0.0-alpha2-00369

Using: Visual Studio Enterprise 2019 - 16.10.31402.337
Project: WebApp.csproj

Creating Workspace ...
Loading project ...
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop:   Failure: Msbuild failed when processing the file 'E:\Workspaces\WebApp.csproj' with message: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.  E:\Workspaces\WebApp.csproj

**Comment by valeriob** [comment]
Here is the fix : https://github.com/T4MVC/R4MVC/pull/162
@artiomchi can you publish a new version pls ?

**Comment by rbsdotnet** [comment]
@valeriob
Thanks for fixing the error.

@artiomchi  Please Release a New Version!!!

**Comment by jkatsiotis** [comment]
+1 on this one from me.

//cc @artiomchi

**Comment by metafab** [comment]
This error does not come from R4MVC. It can be solved by updating the _MSBuildSDKsPath_ environment variable so that it points to the new SDK that was installed with the Visual Studio update. The value must be something like _C:\Program Files\dotnet\sdk\5.0.301\Sdks_.

**Comment by rbsdotnet** [comment]
@metafab 
**Thanks for the tips
The problem was solved using your solution**

**Comment by artiomchi** [comment]
New library build was pushed live! Sorry for the delay :)
