### ISSUE TITLE
Settings and customisations

### ISSUE THREAD

**Issue by wwwlicious** [T4MVC/R4MVC#20]
So T4MVC uses an xml file, gen'd if it doesn't exist and otherwise left untouched between updates 

I think a r4mvc.json file is probably the most natural vnext translation to hold some of the common settings like helper namespace and staticfile folders.

One other possibility to allow customisations/configuration is by providing either delegates or method overrides accessible in the R4MvcCompiler class where string settings cannot easily accomplish this. e.g.

``` csharp
// R4MVC project
public class R4MVCCompilerModule : ICompileModule
{
  private Func<string> getFilePath;
  ....
  private string GetGeneratedFilePath(Project project)
  {
    return this.getFilePath == null ? Path.Combine(project.ProjectDirectory, SyntaxHelpers.R4MvcFileName) : this.getFilePath.Invoke();
  }

  protected void SetGeneratedFilePath(Func<string> filePath)
  {
    this.getFilePath = filePath;
  }
}

// target project
public class R4MvcCompiler : R4MVCCompilerModule
{
  public R4MvcCompiler()
  {
    // user can pass in their own delegate
    this.SetGeneratedFilePath(() => @"c:\mycustompath\gen.cs");
  }
}
```

**Comment by kevinkuszyk** [comment]
I think a `r4mvc.json` file for settings make sense.  There is a new [configuration library](https://github.com/aspnet/Configuration) which we should consider using.

I'm not so sure about using delegates.  Did you have something in mind which would be difficult to store in a `.json` file?

**Comment by wwwlicious** [comment]
one discussion I saw on T4MVC mentioned the timestamping of scripts but off the top of my head...

1. changing the type to find for controllers, maybe you use your own controller class, maybe a framework other than mvc altogether. 
2. swapping out the conventions or methods of viewdiscovery (things like feature folder or just your own viewengine, or spark, or nancy etc)
3. swapping out the conventions for locating and registering IModelUnbinders in mvc DI (hooray I thought of a possible DI use, registering and getting modelunbinders! :)
4. swapping out the conventions for virtualpathprovider
5. swapping out the conventions for finding staticcontent in the wwwroot.

I guess I'm thinking along the lines that.... none of this was easy or possible in t4mvc, because you never had a class like the generator from the get go, and secondly whilst we can pick the standards for all conventions based on default projects, many do not, so going forward baking this kind of pluggability into the compilermodule will require less frequent changes to the core codebase and users more freedom to extend and customise it to their needs.

any finally, whilst you probably *can* do this kind of things in a string unless it really is config (stuff that changes per environment/build config) it's much cleaner not to have *magic strings* in the config right, cos that's what r4mvc is for right?! :)

**Comment by kevinkuszyk** [comment]
Yes, good point.

I was pondering some extensibility mechanism to allow users to replace the logic for finding controllers and views.  I hadn't thought about `IModelUnbinders`, virtual path providers, or static content yet, but they all make sense too.

I'd call this extensibility though, rather than config.  I can imagine a mechanism similar to the view engine registration in MVC, where users can clear out or add to our default implementations and replace them with their own custom versions.  I'm not sure where the hook would be yet, but I think it does make sense to bake it in at v1 if we can.

> any finally, whilst you probably can do this kind of things in a string unless it really is config (stuff that changes per environment/build config) it's much cleaner not to have magic strings in the config , cos that's what r4mvc is for right?! :)

And yes, no magic strings please ;) !

**Comment by wwwlicious** [comment]
ok, I have been experimenting with using DI for extensibility. I've [commented on some of my thought processes] (https://github.com/wwwlicious/R4MVC/blob/adding_views_to_generated_file/src/R4MvcHostApp/Compiler/Preprocess/R4MvcCompiler.cs#L12) so feedback/corrections welcome :)

**Comment by kevinkuszyk** [comment]
@artiomchi do you think we have this covered allready?

**Comment by artiomchi** [comment]
The configuration part has been handled.. But this issue also mentions extensibility, which is an interesting point, but a whole separate thing. We can either keep this open for the time being, or migrate it to a new dedicated issue to keep things clear and avoid confusion..? I'm not sure if it would be used a lot, but the idea of dynamically injecting assemblies with alternative implementations of some of the services (static file providers, model unbinders etc), might be interesting.

It would be a backlog issue though, not for alpha 1

**Comment by kevinkuszyk** [comment]
Closing, as settings are done.  We now have #53 to track adding customisation.
