### ISSUE TITLE
Generator is including too many controllers

### ISSUE THREAD

**Issue by kevinkuszyk** [T4MVC/R4MVC#26]
We seem to have a bug where the generator is including too many controllers.

I cleaned out the `R4Mvc.generated.cs` file and pushed it [here](https://github.com/T4MVC/R4MVC/blob/%2325-generator-is-incuding-too-many-controllers/src/R4MvcHostApp/R4Mvc.generated.cs), so you can see what is produced on my machine.

I don't think we were seeing this on the AppVeyor build before, but it is showing [now](https://ci.appveyor.com/project/T4MVC/r4mvc/build/47#L2353)

**Comment by wwwlicious** [comment]
I noticed this too but deleting the file and re-generating it seems to correct it. I'll try and figure out what is causing it.

**Comment by wwwlicious** [comment]
I've only had this happen locally a couple of times so can't reliably replicate it. 

I suspect it is related to either the k runtime caching something (so I've tried to avoid initialising fields outwith the constructors) or to the preprocessor directives for ASPNETCORE not being available in appveyor.

It also doesn't help that the compilation is running twice for each framework. The first time is usually to modify the controllers and generate the file. I think this then triggers a second compilaton as the compiler has changed but I don't know how to pass the syntaxtree updates the compiler so it doesn't fire a second time. Reassigning the compiler passed to the beforecompile method doesn't seem to do this as I'd hoped.
