### ISSUE TITLE
Fix running unit tests on the build server

### ISSUE THREAD

**Issue by kevinkuszyk** [T4MVC/R4MVC#28]
We need to enable running unit tests on the build server.

I think we had some conflicts with the AppVeyor built in test test discovery and runner.  At the moment we are not running tests using `k test` or AppVeyor's built in test runner.

**Comment by wwwlicious** [comment]
Have you had any luck getting this running?

If not maybe we should ask MS on this as it seems like a roadblock for us, they did say they would like to hear about any roadblocks we encountered?

**Comment by kevinkuszyk** [comment]
I haven't had much time to look at this yet I'm afraid.  I tried to re-enable running unit tests from the build script this morning - but it looks like the build is [broken](https://ci.appveyor.com/project/T4MVC/r4mvc/build/66).

I'm going to focus on getting a stable build first (see #27), and then come back to this.

**Comment by kevinkuszyk** [comment]
I've been doing some research on this today.  We have blocker, in that the xUnit runner only supports Team City at the moment (see this [issue](https://github.com/xunit/aspnet.xunit/issues/3)).

There is some thinking that app developers only need to run their tests against the `net45` framework, because if it runs there, it *should* run on `coreclr` too (see this [comment](https://github.com/aspnet/Testing/issues/34#issuecomment-47443922)).

I'm not sure this applies to us though, as we will be running in the framework.  Maybe a good start would be running tests against `net45` so we can report results to AppVeyor and switching to both frameworks when it is fully supported.

Thoughts?

**Comment by wwwlicious** [comment]
Agreed, actually just tested this and I can get the console runner to work but not VS test runner, debugging will likely be awkward though.

=== TEST EXECUTION SUMMARY ===
   R4Mvc.Test  Total: 33, Errors: 0, Failed: 9, Skipped: 0, Time: 0.858s
PM> k test
xUnit.net ASP.NET test runner (32-bit Asp.Net 5.0)
Copyright (C) 2015 Outercurve Foundation.

Discovering: R4Mvc.Test
Discovered:  R4Mvc.Test
Starting:    R4Mvc.Test
Finished:    R4Mvc.Test

=== TEST EXECUTION SUMMARY ===
   R4Mvc.Test  Total: 33, Errors: 0, Failed: 0, Skipped: 0, Time: 0.811s

**Comment by kevinkuszyk** [comment]
Are you having any problems running your tests?  Since upgrading to CTP6 and the beta3 runtime I get a   NullReferenceException from `k run`:

````
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xunit.ConsoleClient.Program.Main(String[] args)
````

**Comment by wwwlicious** [comment]
I've been fighting a broken install of ctp6 and beta 3 for 3 days now so I haven't looked at this. I'm hopeful that I'll have vs back tonight and plan to spend some time over the weekend finalising the Links statics and will also have a look at fixing the tests.

**Comment by kevinkuszyk** [comment]
The trick seems to be keeping the packages and framework on the same beta version. 

I have the master branch running on beta3 now, so sync that with your fork when you can.  You may need to run kpm upgrade to pull down the latest runtime.

I also fixed running the tests - just fix the xunit runner to beta3.  I'll commit this next time I'm at a machine with VS installed.

**Comment by kevinkuszyk** [comment]
We now have tests running for both `clr` and `coreclr` and results displaying in AppVeyor.
