### ISSUE TITLE
SPIKE: How to unit test R4MVC?

### ISSUE THREAD

**Issue by kevinkuszyk** [T4MVC/R4MVC#3]
We need to figure out how to unit test R4MVC.

The entry point is currently a `CSharpCompilation`, but it may be more useful to use the `IBeforeCompileContext` instead.  Questions:
1. Which is the better choice for the entry point?
2. How to new up a fake `CSharpCompilation` or `IBeforeCompileContext` to invoke the generator?

**Comment by wwwlicious** [comment]
I see that you have switched to the IBeforeCompileContext already which I think this is the better choice as you get access to the target project from which you get the root namespace. Also useful for getting the project file etc.

I've been thinking about how to test without needing to write things to disk. I think the tests would be clearest by parsing strings of test code into SyntaxTree's then passing them to the compilermodules, syntaxrewriters or generators.

I can wrap any calls to System.IO in something mockable which is passed in or overridden in the CompilerModule. The generators and syntaxrewriters etc would just return syntaxtrees which can then be inspected for assertions. 

I'm not able to get VS to recognise the single skipped unit test at the moment either, it looks similar to the issues I've had with other projects in VS 2015 CTP complaining about not knowing what System.Object is. No idea why?!

![image](https://cloud.githubusercontent.com/assets/908801/6158881/e75ecc4a-b246-11e4-9e69-8171ee3a24a4.png)

**Comment by kevinkuszyk** [comment]
Apparently, there is a problem with xUnit in VS 2015 CTP5.  See this [issue](https://github.com/aspnet/Testing/issues/65)

I had it working yesterday, but it's broken again today and I can't remember what I did yesterday.

I just tried this [workaround](https://github.com/aspnet/Testing/issues/65#issuecomment-73198145) and most of my intelisense is back:

![image](https://cloud.githubusercontent.com/assets/2734580/6176526/7f863818-b2f7-11e4-9321-1943a5d2efc8.png)

**Comment by wwwlicious** [comment]
I've still no luck with getting unit tests to run in VS. It looks like this [isn't supported yet](https://github.com/xunit/visualstudio.xunit/issues/41) 
[MS Connect Bug](https://connect.microsoft.com/VisualStudio/feedback/details/1099770/test-explorer-does-not-discover-tests-in-project)

**Comment by kevinkuszyk** [comment]
Thanks for that - I hadn't realised that running tests in the IDE had been pulled for the CTP 5.  We'll just have to run them the old fashioned way from the command line for now.

On a positive note, my VS intelisense is working again without using any workarounds.

**Comment by artiomchi** [comment]
Since the project will now be a cli/powershell executable, unit testing it will work the same as unit testing any other app (in fact, unit tests are already picked up by AppVeyor), so seems like this can be closed as well

**Comment by kevinkuszyk** [comment]
@artiomchi agreed.
