### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by robertbird** [T4MVC/R4MVC#39]
I have just started playing with ASP.Net 5 and MVC 6, after creating a new project I instinctively added T4MVC and quickly found my way here! :+1: 

I see from the latest comments [here](https://github.com/aspnet/Home/issues/272), that MS are going to support single file generators and that T4 may not be dead.

I'm wondering how close you guys are? Activity seems to have dropped off, is this related to the T4 news? It still seems like this project is a good idea going forward.

**Comment by wwwlicious** [comment]
I do plan on picking this up again soon but it's the usual excuses that I've been super busy and haven't had the time over the past six months. Also I've been waiting for both VS2015 RTM which we now have and asp.net 5 / MVC 6 projects to stabilize a bit during the beta's for less of a moving target

I'm haven't really followed the file generators discussion either but agree that this project is worth pursuing.

**Comment by kevinkuszyk** [comment]
For me this is a lower priority now that T4 support is back on the cards. 

I'm happy to remain involved if I can find time for it over the next few months.

In terms of where we're at - @wwwlicious had some code generation working on one of the early beta runtimes.  I have tried to keep up with the betas as they drop, but the last time I checked added a reference to R4MVC from an MVC broke the build.

I can push my branch if you have time to fix it up an move things forward.  Collaborators are always welcome!

**Comment by robertbird** [comment]
Thanks for the honest responses!

I think this project is a great idea and would love to contribute, but have to be honest, I know nothing about Rosyln and am only just starting to learn about vnext so have a long way to go before I would be able to contribute code. I'm also a bit of an all-rounder and can't see myself getting too deep into Roslyn. However, maybe I can help with the docs when you are a bit further down the line :smiley: 

Hopefully as people start investigating and attempting to port real projects over to VNext, you will get a lot more interest and offers for help.

Best of luck,
Rob
