### ISSUE TITLE
Automate deployment to MyGet and NuGet.org

### ISSUE THREAD

**Issue by kevinkuszyk** [T4MVC/R4MVC#49]
Follow on from #48.

- CI builds (all branches except `master` and PRs) should automatically publish to MyGet.
- When we create a tag from `master` (i.e. create a release in GitHub) we should automatically publish to NuGet.org.

**Comment by valeriob** [comment]
Hi, how close is this ? i could help testing it with a consumable package

**Comment by valeriob** [comment]
Stupid followup question, i downloaded the src, linked the project R4Mvc, now how do i cfg and run it ?  :D
Thanks

**Comment by valeriob** [comment]
Meanwhile i'm trying to run it manally, but i get the following error :
 Msbuild failed when processing the file 'C:\Users\vborioni\Downloads\R4MVC-master (1)\R4MVC-master\src\R4MvcHostApp\R4MvcHostApp.csproj' with message: The imported project "C:\Users\vborioni\Downloads\R4MVC-master (1)\R4MVC-master\src\R4Mvc.Tools\bin\Debug\net462\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\vborioni\Downloads\R4MVC-master (1)\R4MVC-master\src\R4MvcHostApp\R4MvcHostApp.csproj

I'm using Vs 2017, and i have .net core 2.0 preview 2 installed.

**Comment by kevinkuszyk** [comment]
@valeriob getting the package up on MyGet might take a few more weeks (the kids are off at the moment as it's school holidays here in the UK and busy time at the allotments).

@artiomchi any tips for running it locally using a custom build?

**Comment by valeriob** [comment]
Hi,
i tried to set the env variable "MSBuildSDKsPath" to  "c:\Program Files\dotnet\sdk\2.0.0-preview2-006497\Sdks\" but now i get a different error : 
Msbuild failed when processing the file 'C:\Users\vborioni\Downloads\R4MVC-master (1)\R4MVC-master\src\R4MvcHostApp\R4MvcHostApp.csproj' with message: The imported project "C:\Program Files (x86)\MSBuild\2.0\Microsoft.Common.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  c:\Program Files\dotnet\sdk\2.0.0-preview2-006497\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props

I do have that installed, but it looks for msbuild 2.0, i've 14 and 15 installed : 
![image](https://user-images.githubusercontent.com/1522516/28769835-5fd567a4-75dd-11e7-9294-1547775526e7.png)


![image](https://user-images.githubusercontent.com/1522516/28769872-81b76ab6-75dd-11e7-9456-fac9ed4781ee.png)

**Comment by artiomchi** [comment]
Hi @valeriob 

You shouldn't have to change the env variables to build the project. My guess is that you've installed .NET Core 2.0 Preview 2, while I build it against 1.1. In any case, I'll be making sure that it works when build against 2.0 shortly.

Regarding your question about adding it to an existing project, I've set up a MyGet feed against my dev branch, so until we have official alpha builds, you could just use my nightlies in the meantime.

You can add the following to your NuGet feeds: https://www.myget.org/F/artiomchi/api/v3/index.json

Then reference R4Mvc and R4Mvc.Tools in your web project.  
Once installed, you can run the `Generate-R4MVC` PowerShell command in the `Package Manager Console` window in VS to re-generate the classes.

**Comment by artiomchi** [comment]
P.S. If you have any issues with the nightly builds or building the code, please open a new issue so that we can help you. I'd rather we keep the issue discussions on topic :)

**Comment by valeriob** [comment]
Hi @artiomchi thanks !
I migrated r4mvc to aspnetcore 2.0 but i failed... Well i migrated it and it compiles, but running the tool brings the result you see on  my comment above 😄

**Comment by artiomchi** [comment]
@kevinkuszyk Once you update the API keys in the yaml file, this issue can be closed too :smile:

**Comment by kevinkuszyk** [comment]
@artiomchi what's your NuGet.org username, so I can add you as an owner of the package?

**Comment by artiomchi** [comment]
@kevinkuszyk it's ArtiomChi, same as here :)

Also, thanks for that. That would let me update the release notes after deployments!

**Comment by kevinkuszyk** [comment]
Done.

Re. release notes - I usually just add them to the tag in GitHub, and put a link to the GitHub releases page in the `.nuspec`.
