### ISSUE TITLE
Alpha1 release planning

### ISSUE THREAD

**Issue by kevinkuszyk** [T4MVC/R4MVC#50]
@artiomchi I've created a [milestone](https://github.com/T4MVC/R4MVC/milestone/2) and moved the issues I think we need for a first alpha into it.  Do you think there is anything else to add?  There is also the [v1 backlog](https://github.com/T4MVC/R4MVC/milestone/3) for other items to be picked up in later alphas and betas, and a [backlog](https://github.com/T4MVC/R4MVC/milestone/1) for anything else after v1.

@davidebbo I'm going to setup some automated deployments to MyGet / NuGet.org soon (see #49).  Would you like to be listed as a package owner on NuGet (you are an owner here after all)?

/cc @wwwlicious

**Comment by artiomchi** [comment]
The project should be almost ready for alpha1, actually.

#20 and #4 can actually be moved to the v1 backlog, as they're not critical for the alpha. Other than testing a couple issues, the current codebase should work, and has 90% of the core features already. I'd potentially consider #13 and #33 for at least `alpha.2` if not `alpha.1`.

The issues I want to add to the alpha.1 milestone at this point are #51 (just to make sure that part of the code is stable and consistent) and #52 (the simple first workaround with the uninstall script, and once released we'll move #52 to the v1 backlog for a final solution)

P.S. I'll be a bit busy in the coming two weeks, so my progress will be a little slower, but I'm still 100% committed to the project. We should be able to go ahead with alpha one early next week, at which point I'll start working on cleaning the code and adding unit tests.

**Comment by kevinkuszyk** [comment]
@artiomchi thanks for your efforts so far.  I'll try to find some time over the next week or so to get the CI sorted.

**Comment by artiomchi** [comment]
@kevinkuszyk @davidebbo  
Since the alpha1 release is basically impending, I thought to bring the last thing we should do before pushing the package to NuGet - the package description.

I'm just pushing a commit that cleans up the .csproj on both packages, separating the metadata in a separate property group. I've based the metadata on the current T4MVC packages, since it's practically the same project, with just small adjustments.

Here's what I have so far:

![image](https://user-images.githubusercontent.com/822898/29114573-af185702-7cec-11e7-9167-70be4002f964.png)

The description on T4Mvc.Tools is:
> R4Mvc is a tool that generates strongly typed helpers for ASP.NET Core MVC.

**Comment by kevinkuszyk** [comment]
@artiomchi  looks good.  A couple of questions:

1. Are we going to set the initial version to `1.0.0-alpha1`?
2. Can you include Scott Mackay (@wwwlicious) as an author - he wrote most of the original code.
3. Do you want to add yourself as an author and owner?  Once we push to NuGet.org I'll add you as an owner of the package there too.

And on the subject of deployments, this is an encrypted API key for nuget.org:
```
oK/7qSZDyR1umPtWP8zAswwPfIE0FJPeEkkQQMRKj6e6eq0tdEIwbPh37lGBDeSi
```

For MyGet, yes I already created an account.  The push url is 

```
https://www.myget.org/F/r4mvc/api/v2/package
```
and encrypted API key:

```
DdgwyUm4/aaCfk28jRGRFgQpqcCp6OvuqCZLZaHjNAPHZuia0+PF01zC8JGpWfe7
```

**Comment by artiomchi** [comment]
@kevinkuszyk I was going to keep it at pre 1.0 until we're closer to having the full implementation.. The current first alpha is a bit raw around the edges, and while it's usable, it's still missing a lot of the original functionality in T4MVC, like extensibility, for example.. It also requires some work around tooling (esp the dotnet cli part) which also influenced that decision... 

Once I'm more confident with the reliability and we have most of the core functionality in place, we'll up the version to 1.0. Does that sound ok?

Re: author/owner, I can set the Authors field to
> Kevin Kuszyk, Scott Mackay, Artiom Chilaru

The owner field can either be set to David, or we can leave it blank (which will copy the value above, and will be overridden anyway in nuget.org)

Does that sound good?

**Comment by kevinkuszyk** [comment]
I'd be happy to start at `1.0.0-alpha1` or `0.1.0-alpha1`.  I can't remember where `0.6.0` came from to be honest.

**Comment by artiomchi** [comment]
I believe I started with version 0.5 when I rebuilt the projects, and was slowly increasing it as I was adding more features.

I'm OK with bumping it to 1.0 for the alpha then. I'll finish up some tests to make sure it's usable, and deploy the alpha build in the coming days!

**Comment by artiomchi** [comment]
@kevinkuszyk @davidebbo @wwwlicious 
Alpha1 release is finally out and deployed to NuGet! I've put some basic docs up, so that should allow some people to start using and testing it. 

In the meantime, I'm switching gears to prepare for alpha 1.1, where I'll concentrate on code restructuring, cleanup and testing, while we gather some feedback from the alpha testers :smile:
