### ISSUE TITLE
Prevent Area and Root controller name clashes

### ISSUE THREAD

**Issue by artiomchi** [T4MVC/R4MVC#51]
One of the things that should be tackled is preventing the root controllers and area names from clashing.

Say a user has a `CatalogsController`, and also a `Catalogs` area with further controllers. The MVC class would have a `MVC.Catalogs` field for the controller and a `MVC.Catalogs` property for the area. 

I've added a basic check for this, and will rename the area property in the MVC class to `MVC.CatalogsArea`. All other areas (that don't clash) don't get the suffix.

If someone has a `CatalogsAreaController` or a `CatalogsArea` area this will of course cause a clash, but I'm not handling that, since there's no practical reason to have a controller or area named this way :)

Does that sound reasonable?

(a patch to finish this logic will be in the next pull request late this week)

**Comment by kevinkuszyk** [comment]
Closed via #55.
