### ISSUE TITLE
Add support for / migrate to AspNetCore 2.0

### ISSUE THREAD

**Issue by artiomchi** [T4MVC/R4MVC#58]
An obvious move eventually, but there are a couple things blocking us, currently.

1. Issues with MsBuild (outlined in #57). A blocking issue that will affect users when trying to run our module. Pretty much priority 1 for this issue.
2. AppVeyor support for .NET Core 2.0.

Issue one will have to be handled first. Luckily, I managed to get it to work (sort of) on a clean environment, with a small workaround. Currently I have the sdk path (with the build number) hardcoded in the app. I could add a small method to "autoconfigure" and point to the latest available build, until the final release is out, or the MSBuild bug is fixed.

Issue 2 is also manageable, since you can technically install the runtime as part of the AppVeyor script. Again, this would only be required until the final public release is out.

**Comment by artiomchi** [comment]
Tagging @valeriob to keep him updated

**Comment by artiomchi** [comment]
@valeriob - I've just pushed the first alpha release, but alongside that, I also pushed a first ci build of the dotnet 2 branch.

You can find these builds under this MyGet repo: https://www.myget.org/F/r4mvc/api/v3/index.json

Look for the `*-ci-dotnet-core-2-*` builds!

**Comment by artiomchi** [comment]
@valeriob (btw, I suggest you subscribe to this issue, so I don't have to tag you every time :wink: )

AspNetCore MVC 2.0 was just pushed to NuGet.. I'm not sure if that's an accidental early release, but you can see it for yourself here: https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc/

**Comment by artiomchi** [comment]
Also I just found an unpublished link to the final .NET Core 2.0 files as well! I think an announcement is coming!

Edit: Not sure about the framework yet, but seems like .NET Standard 2.0 has been finalised - that that's something

Edit 2: Ahh, apparently it'll be released on Sep 18th, confirmed here: https://www.youtube.com/watch?v=fGxGeP7b8j0

**Comment by valeriob** [comment]
Ofc i'm subscibed thanks! 😄 
Yep, in a few days maybe we will have the final bits of netstandard2.0, netcore2.0, aspnetcore2.0, vs 15.3.

**Comment by artiomchi** [comment]
One piece of interesting news regarding this issue - I've done some tests, and I just realised that the R4MVC project doesn't actually need to reference AspNetCore 2.0 - as long as it references 1.1+, you can actually reference it in your AspNetCore 2.0 project, and it should still work!

With this in mind, I suggest you try reference the alpha1 build from NuGet directly, add the Environment variable from #57, restart VS (to make sure VS picked up the latest env variable), and then run the generator. This doesn't guarantee success yet, I've had some mixed results with the fix.

Looking forward to your test result! :)

**Comment by artiomchi** [comment]
NVM, I just pushed a new build that I've just confirmed to work on both AspNetCore 1.1 and 2.0!

Look out for `1.0.0-alpha1-00166`

**Comment by valeriob** [comment]
thanks @artiomchi !
I guess that as long as the assembly Microsoft.AspNetCore.Mvc.Abstractions does not change much we're good !

**Comment by artiomchi** [comment]
Oh, they won't change any of the core classes. I've already encountered this in the past, Microsoft (rightly so) are very much against changing existing public APIs unless there's a VERY massive need for this, as this would break existing libraries and projects. So that's actually safe to do.

In the future, we'll eventually raise the minimum version anyway, but only when v2 is the norm, and nobody uses v1 :)

With that said, since we don't have to do anything else for v2 support, as it should just work out of the box, I'm closing this issue (and dropping the related branch)

**Comment by MichaelCave** [comment]
Quick Question, I am using .Net Framework 4.6.1. SHould I use R4MVC or T4MVC or is R4MVC the natural successor of T4MVC?
THanks

**Comment by artiomchi** [comment]
It's not really about the .NET framework that you're using - the question is whether you're using ASP.NET or ASP.NET Core? While similar, the latter is a completely different application framework that's been written from scratch.

In the first case you should use T4MVC, and if you're using ASP.NET Core (whether it's .NET Framework or .NET Core) you should use R4MVC
