### ISSUE TITLE
Switching the repository default branch

### ISSUE THREAD

**Issue by artiomchi** [T4MVC/R4MVC#68]
Hey @kevinkuszyk 

Could you change this repository's default branch to `develop`? This is to ensure two things:

 - All pull requests will by default be pointing to the default branch. We don't want an accidental merge into master, triggering a release :)
 - When you go to the home page of the repository, we want to make sure that the users see the latest version of the README file, which will be in the dev branch :)

**Comment by kevinkuszyk** [comment]
Done.  I also made `develop` and `master` protected.
