### ISSUE TITLE
Generate partial controller classes

### ISSUE THREAD

**Issue by kevinkuszyk** [T4MVC/R4MVC#7]
We need to generate partial controller classes to hold the view and action name constants.

**Comment by wwwlicious** [comment]
For modifying existing partial classes I used a ControllerRewriter with an override for VisitClassDeclaration

The classes are marked as partial [here](https://github.com/wwwlicious/R4MVC/blob/master/src/R4Mvc/ControllerRewriter.cs#L41)

Currently I rely on the semantic model to get the declaring type which in turn I use to determine if the class is an MVC controller class. 

An issue with this is that once you update the node, it invalides the CompilationUnit in the syntax tree and my override for VisitMemberDeclaration will not be able to get the semantic model for the member (which again I use to determine if this is an MVC Controller member)

I am investigating how to avoid using the semantic model for type resolution but this appears pretty difficult vs creating a new compilation unit for the syntaxnode passed to the VisitMemberDeclaration override

**Comment by wwwlicious** [comment]
I use the ControllerRewriter to help build a list of the Controller class SynxtaxNodes that I need to build
[Example here](https://github.com/wwwlicious/R4MVC/blob/master/src/R4Mvc/R4MvcPreCompileModule.cs#L39)

This outputs all the controller syntaxnode information which I can then pass to a generator and cycle through to generate each class and methods, derived class etc
[Example here](https://github.com/wwwlicious/R4MVC/blob/master/src/R4Mvc/R4MvcGenerator.cs#L36)


I've gone for a fixed generated file in a subfolder called R4MVC located in the directory of the first controller in it's list. The file contains all the generated code as this makes it easy to filter out of the ControllerRewriter and reduces the risk of orphans from removed or changed code as the file is generated fresh every time without seeming like it affects perf too much.
