### ISSUE TITLE
Gitter for discussions?

### ISSUE THREAD

**Issue by artiomchi** [T4MVC/R4MVC#71]
Hey @kevinkuszyk @wwwlicious @valeriob,

I thought it would be useful to have some way to have more live discussions on smaller scale, other than the issue tracker, as well as to have a place where users could ask questions in the future? Some (smaller) things are easier to discuss _live_, instead of in comments to an issue

I saw that a number of projects started using Gitter, so I thought maybe that could be useful? What do you think?

I created this for now (https://gitter.im/R4Mvc/Lobby), although I guess if other people join and think it's a good idea, it might be better to create a T4MVC one, and use it for both projects (more adoption, easier to find, mostly identical/similar functionality)

**Comment by kevinkuszyk** [comment]
@artiomchi good idea.  I've not used it myself, but I've seen a number of other projects using it.
