### ISSUE TITLE
New post from Hanselman on T4MVC/R4MVC

### ISSUE THREAD

**Issue by davidebbo** [T4MVC/R4MVC#73]
https://www.hanselman.com/blog/T4MVCAndR4MVCRoslynCodeGeneratorsForASPNETCoreTagHelpers.aspx

I assume you guys saw this. Pretty cool to see coverage of the work you guys are doing!

**Comment by artiomchi** [comment]
Oh man, this is awesome!

The pressure is on! I better double up my efforts 😁

**Comment by davidebbo** [comment]
Sorry, that I can't be involved in R4MVC the way I was with T4MVC, but it's awesome that you guys are doing that!

**Comment by kevinkuszyk** [comment]
@davidebbo thanks for the heads up.  I hadn't seen that (I was off grid in a field all weekend!).

I'm curious - did Hanselman find this project organically, or did you point him in the right direction?

> Oh man, this is awesome!
>
> The pressure is on! I better double up my efforts 😁

@artiomchi keep up the good work!

**Comment by davidebbo** [comment]
Nope I had nothing to do with it! :)

**Comment by valeriob** [comment]
I pointed him to this project because i think that aspnet core should have THIS way to generate links in the framework 😄 
And i asked him to find some help to help the project grow 😄
