### ISSUE TITLE
Extra packages on MyGet being ordered above the latest CI build

### ISSUE THREAD

**Issue by artiomchi** [T4MVC/R4MVC#74]
Hey @kevinkuszyk,

Could I ask you to remove some of the published packages on MyGet?

During early deployment tests, AppVeyor ended up accidentally deploying some Microsoft.* packages to our MyGet, which we should probably remove.

Also, unfortunately NuGet thinks that `1.0.0-ci-vscommunity-path-00164` is newer than `1.0.0-ci-00190`.
We have two "feature" builds on there for each of the packages that end up identified as the "latest" builds.

I've updated the appveyor code so that new feature branch builds will get a double dash before the branch name, putting them below the mainstream CI builds, but could you also remove these two builds from MyGet? (`1.0.0-ci-vscommunity-path-00164` and `1.0.0-ci-dotnet-core-2-00158`)

Thanks

**Comment by kevinkuszyk** [comment]
@artiomchi all done.
