### ISSUE TITLE
mvc-action not working

### ISSUE THREAD

**Issue by yaseralnajjar** [T4MVC/R4MVC#77]
Hi,

I just downloaded the latest package of R4MVC with R4MVC.Tools (1.0.0-alpha1-00187) in an **asp-core 1.1 project**.

Everything works fine till I try to use the tag helper **mvc-action** (it does not show in the same color **asp-for**), and it handles it as a normal html attribute.

If you can't replicate the problem, I can send the project on email.

**Comment by yaseralnajjar** [comment]
Already sent the project to the author email address.

**Comment by artiomchi** [comment]
One thing you need to do to make the rag helpers work is register the tag helpers in your project. You do this by adding the following to your `_ViewImports.cshtml` file:
```razor
@addTagHelper *, R4Mvc
```

See here for example: https://github.com/T4MVC/R4MVC/blob/develop/src/R4MvcHostApp/Views/_ViewImports.cshtml

**Comment by kevinkuszyk** [comment]
@0xRumple did @artiomchi's suggestion fix your issue?

**Comment by yaseralnajjar** [comment]
I haven't tried yet... last time I added the package to my project it gave me a CGI error. I will try again once my project is done to get rid of the hardcoded controllers and actions.

But @artiomchi's suggestion seems absolutely right since I haven't added the taghelper in my viewimports.

**Comment by artiomchi** [comment]
I'm going to assume that my suggestion pointed you in the right direction, solving the problem.

As such I'm closing this issue - feel free to re-open if it needs further discussion.
