### ISSUE TITLE
Can't find r4mvc.json

### ISSUE THREAD

**Issue by wmcainsh** [T4MVC/R4MVC#81]
I've installed R4Mvc and R4Mvc.Tools but can't find the config file.

Is this still to be implemented or should it be manually created?

**Comment by kevinkuszyk** [comment]
That file should be there.  @artiomchi any idea what happened here?

**Comment by artiomchi** [comment]
At the moment the r4mvc.json file has to be manually created. All the options in the configuration have defaults, so this file is there for overrides (at the moment).

During the next sprint I'll change the generator so that it creates this file and populates it with current options.

**Comment by artiomchi** [comment]
This was now implemented, and is present in the CI build.
