### ISSUE TITLE
Does not generate valid code when controller method return value is not (I)ActionResult

### ISSUE THREAD

**Issue by mnmr** [T4MVC/R4MVC#83]
Methods that return an explicit JsonResult (or any other IActionResult derivative), the generated code does not compile.

**Comment by artiomchi** [comment]
To be perfectly honest, while possible, I don't see any good reason to use anything other than IActionResult as a return type. It just restricts the dev's options.

But some people might have a reason to do that, so let's add it! I'd have to add individual classes for each type override, so I'll be adding code for the `ActionResult`, `JsonResult`, `ContentResult`, `RedirectResult`, `RedirectToActionResult`, `RedirectToRouteResult`. That should cover just about any basic case, and for anything non-standard - the customer would have to use an `IActionResult` return type
