### ISSUE TITLE
Generate helper methods on generated partial controllers

### ISSUE THREAD

**Issue by kevinkuszyk** [T4MVC/R4MVC#9]
We need to generate some boilerplate helper methods on our generated partial controllers.  

These are the methods added by T4MVC:

``` c#
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
protected RedirectToRouteResult RedirectToAction(ActionResult result)
{
    var callInfo = result.GetT4MVCResult();
    return RedirectToRoute(callInfo.RouteValueDictionary);
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
{
    return RedirectToAction(taskResult.Result);
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
{
    var callInfo = result.GetT4MVCResult();
    return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
{
    return RedirectToActionPermanent(taskResult.Result);
}
```

Do we need to keep the `[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]` attributes?

**Comment by wwwlicious** [comment]
Yes, I think keeping the attributes helps for a couple of scenarios.

For coverage/inspections tooling, generatedCode is pretty common to ignore as gen'd code is normally pretty heinous in the formatting and fxcop/stylecop etc type standards
A side benefit, although so far I don't it's needed, is that the gencode attribute can be used to either filter out or specifically target R4MVC gen'd files/code

The debuggernonusercode is also good to stop it from appearing is users debug sessions as it will rarely be relevant to do so ... once R4MVC is complete and stable that is! :)

**Comment by kevinkuszyk** [comment]
Good point.  Let's keep them in.
