### ISSUE TITLE
Add tag helper registration instructions to documentation

### ISSUE THREAD

**Issue by BrianSchroer** [T4MVC/R4MVC#94]
It took me a while to figure out that I had to add `@addTagHelper *, R4Mvc` to _ViewImports.cshtml.

It looks like I'm not the first to have difficulty with that (see [issue 77](77)).

I've submitted a pull request to add instructions for that to the README.

**Comment by artiomchi** [comment]
Absolutely! I really should have gotten to that earlier.

I'll try update the installer script to add that automatically on package install, actually :)
