### ISSUE TITLE
Consider removing package dependencies from the R4Mvc.Tools project

### ISSUE THREAD

**Issue by valeriob** [T4MVC/R4MVC#98]
Adding r4mvc.tools to aspnet core 2.1 rc1 project it causes package conflict that is not really needed.
I think it should be very quick fix to remove all the dependant packges from r4mvc.tool nuget package because it does not need them to run.

> All packages and projects are compatible with .NETFramework,Version=v4.7.1 (win7-x64).
NU1107: Version conflict detected for Microsoft.CodeAnalysis.CSharp. Reference the package directly from the project to resolve this issue. 
 OnRtls.Web -> Microsoft.AspNetCore.Mvc.Razor.ViewCompilation 2.1.0-rc1-final -> Microsoft.AspNetCore.Mvc.RazorPages 2.1.0-rc1-final -> Microsoft.AspNetCore.Mvc.Razor 2.1.0-rc1-final -> Microsoft.CodeAnalysis.CSharp (>= 2.8.0-beta3) 
 OnRtls.Web -> R4Mvc.Tools 1.0.0-ci-00259 -> Microsoft.CodeAnalysis.CSharp.Workspaces 2.6.1 -> Microsoft.CodeAnalysis.CSharp (= 2.6.1).
Failed to resolve all items referenced by 'MyProject.csproj'. This message can typically be ignored. The issue may be resolved by fully restoring and building the solution. If the unresolved item is a project reference this can lead to an incomplete NuGet restore result and missing package references. To ensure that restore is able to find all projects verify that all projects are referenced correctly and exist on disk.
Package restore failed. Rolling back package changes for

**Comment by artiomchi** [comment]
This is actually a pretty interesting one.

The way the tools project works right now is by taking the full output of the project, including all the dependant libraries, to run the build.

Ideally, the project should be pulling them from NuGet on the developer's side - this would have two major benefits:

1. We wouldn't have to bundle MSBuild with R4Mvc.Tools (so the package would be considerably smaller)
2. You could easily reference a newer version of, say, MSBuild in your machine, forcing our tool to use it instead, so issues like #99 wouldn't require a new release!

At the moment we're a bit of a ways away from being able to do that, unfortunately :(

**Comment by artiomchi** [comment]
So I've been looking more into this, and went again through some of Microsoft's documentation.

Since we bundle all assemblies alongside our executable, our NuGet package doesn't need to reference it's dependencies - it's self container. And the new csproj format has a very simple way of specifying this.

So the next build of R4Mvc.Tools won't have any package dependencies, which should stop the above issue from happening

**Comment by valeriob** [comment]
Exactly, thanks !
